- hosts: prometheus
  connection: local
  become_user: root
  become: yes
#  pre_tasks:
  vars:
    product: "prometheus"
    userId: "{{product}}"
    groupId: "{{product}}"
    exec_command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.conf --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d"
    version: "2.3.2"
  roles:
    - { role: yum, tags: yum }
    - { role: docker, tags: docker }
    - { role: prometheus, tags: prometheus }